site_name: WLED Project
site_author: Christian Schwinne (Aircoookie)
#site_url: https://wled.app
repo_name: WLED
repo_url: https://github.com/Aircoookie/WLED
repo_title: WLED Repository
#copyright: Copyright &copy; 2016-2021 Christian Schwinne, Contributors
edit_uri: https://github.com/Aircoookie/WLED-Docs/edit/main/docs
theme:
  name: material
  custom_dir: docs/assets/overrides
  language: en
  favicon: assets/images/ui/aircoookie/blurple.png
  logo: assets/images/ui/akemi/001_cheerful.png
  icon: 
    repo: fontawesome/brands/github
  features: 
    - navigation.top
    # - navigation.expand
    - navigation.instant
    - navigation.tabs
    - content.action.edit
    # - toc.integrate
  palette:
    - scheme: wled
      primary: cyan #mostly overriden in extra.css
      accent: orange
      toggle: 
        icon: material/weather-sunny
        name: Light Mode
    - scheme: default
      primary: orange
      accent: orange
      toggle: 
        icon: material/weather-night
        name: Dark Mode
plugins: 
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/QAh7wJHrRM
      name: Discord
    - icon: fontawesome/brands/discourse
      link: https://wled.discourse.group/
      name: Forum
    - icon: fontawesome/solid/code
      link: https://gitpod.io/#https://github.com/Aircoookie/WLED
      name: Gitpod
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wled_project/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/results?search_query=WLED
    - icon: fontawesome/solid/shirt
      link: https://wled.teemill.com/
    - icon: fontawesome/solid/heart
      link: https://paypal.me/aircoookie/
  analytics:
    provider: google
    property: G-QSVCRSVM18
extra_css:
  - assets/stylesheets/global.css
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/js/newtab.js
nav:
  - Welcome: index.md
  - Basics:
    - Getting Started: basics/getting-started.md
    - Top 5 mistakes: basics/top5_mistakes.md
    - Compatibility:
      - LED strips: basics/compatible-led-strips.md
      - Controllers: basics/compatible-controllers.md
      - Other Hardware: basics/compatible-hardware.md
      - Software: basics/compatible-software.md
    - Installation:
      - Install WLED Binary: basics/install-binary.md
      - Install using ESP GUI: basics/install-gui.md
      - Compiling WLED: advanced/compiling-wled.md
    - Tutorials: basics/tutorials.md
    - FAQ: basics/faq.md
  - Features:
    - Effects: features/effects.md
    - Palettes: features/palettes.md
    - Macros: features/macros.md
    - Presets: features/presets.md
    - Segments: features/segments.md
    - Settings: features/settings.md
    - Multi-strip Support: features/multi-strip.md
    - Relay Control: features/relay-control.md
    - Web GUI Sitemap: features/subpages.md
    - White handling: features/cct.md
    - Pixel Art Converter: features/pixel-art-converter.md
    - Ethernet (LAN) compatibility: features/ethernet-lan.md
  - Interfaces: 
    - Blynk: interfaces/blynk.md
    - DMX: interfaces/dmx-output.md
    - E1.31 (DMX) / Art-Net: interfaces/e1.31-dmx.md
    - HTTP Request API: interfaces/http-api.md
    - Remote Control: interfaces/infrared.md
    - JSON API: interfaces/json-api.md
    - MQTT: interfaces/mqtt.md
    - Philips Hue: interfaces/philips-hue.md
    - Serial: interfaces/serial.md
    - WLED UDP Sync: interfaces/udp-notifier.md
    - UDP Realtime / tpm2.net: interfaces/udp-realtime.md
    - Websocket: interfaces/websocket.md
    - DDP Realtime: interfaces/ddp.md
  - Advanced:
    - Audio Reactive WLED: advanced/audio-reactive.md
    - Home Automation: advanced/home-automation.md
    - Remote Access / IFTTT: advanced/remote-access-ifttt.md
    - Security: advanced/security.md
    - Wiring Protips: advanced/wiring.md
    - Long Data Lines: advanced/longdata.md
    - Compiling WLED: advanced/compiling-wled.md
    - Custom Features: advanced/custom-features.md
    - ESP32 Recovery: advanced/esp32-recovery.md
    - Mapping: advanced/mapping.md
    - Mixed 2D and 1D Bus: advanced/2d-1d-Mixed-Setup.md
    - Virtual LEDs: advanced/ddp.md
    - Custom Access Point Configuration: advanced/custom-ap.md
    - Using PIR Sensors: advanced/pir-sensors.md
  - About: 
    - Contributors & Credits: about/contributors.md
    - Privacy Policy: about/privacy-policy.md
    - Upcoming Features: about/roadmap.md
